import type { CancellablePromise } from '@wailsio/runtime'
import {
  AuthService,
  MembershipService,
  SystemService,
  TaskService,
} from '../../bindings/github.com/chaunceyxie1/BunkrDownloader/internal/services/index.js'
import type * as Bindings from '../../bindings/github.com/chaunceyxie1/BunkrDownloader/internal/services/index.js'
import type * as Store from '../../bindings/github.com/chaunceyxie1/BunkrDownloader/internal/store/index.js'
import type {
  Aria2Globals,
  AppSettings,
  AuthRes,
  CancelOrderReq,
  CancelOrderRes,
  ChangePasswordReq,
  CreateOrderReq,
  CreateOrderRes,
  CreateTaskReq,
  CreateTaskRes,
  DeleteTaskRes,
  DownloadFile,
  EventLevel,
  FileActionRes,
  FileStatus,
  Health,
  ListEventsQuery,
  ListEventsRes,
  ListFilesQuery,
  ListFilesRes,
  ListOrdersRes,
  ListTasksQuery,
  ListTasksRes,
  LoginReq,
  MembershipStatusRes,
  OkRes,
  Order,
  OrderStatus,
  PayOrderReq,
  PayOrderRes,
  PlanId,
  PlanItem,
  PlansRes,
  Quota,
  RedeemReq,
  RedeemRes,
  RegisterReq,
  Stats,
  Task,
  TaskActionReq,
  TaskActionRes,
  TaskDetailRes,
  TaskEvent,
  TaskOptions,
  TaskStatus,
  User,
} from './types'

/**
 * Transport for the desktop build.
 *
 * Every call goes through the Wails v3 service bindings generated by
 * `wails3 generate bindings`; there is no HTTP and no WebSocket. The service
 * methods return `[value, error]` pairs, so this module keeps the *public*
 * surface of the previous REST client (`authApi`, `membershipApi`, `tasksApi`,
 * `systemApi` + the envelopes in `types.ts`) and adapts the Go models to it.
 * The stores and views are therefore untouched.
 */

/** Kept for import compatibility — no request is ever built from it. */
export const API_BASE = '@wails'

export const TOKEN_KEY = 'bunkr_token'

/** Typed error thrown by every failed service call. */
export class ApiError extends Error {
  readonly status: number
  readonly code: string
  readonly details?: Record<string, unknown>

  constructor(status: number, code: string, message: string, details?: Record<string, unknown>) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.code = code
    this.details = details
  }

  /** True when the session is gone / invalid. */
  get isUnauthorized(): boolean {
    return this.status === 401
  }
}

/**
 * The bindings only carry `code` + `message`, while the app still reads
 * `ApiError.status` (toasts, 404/403 handling in the task store). Map the
 * documented error codes onto the HTTP status they used to carry.
 */
const STATUS_BY_CODE: Record<string, number> = {
  bad_request: 400,
  invalid_url: 400,
  weak_password: 400,
  invalid_code: 400,
  email_taken: 409,
  username_taken: 409,
  invalid_credentials: 401,
  unauthorized: 401,
  forbidden: 403,
  not_found: 404,
  conflict: 409,
  invalid_state: 409,
  quota_exceeded: 429,
  too_many_requests: 429,
  internal_error: 500,
  upstream_error: 502,
  aria2_unavailable: 503,
  network_error: 0,
}

function statusForCode(code: string): number {
  const mapped = STATUS_BY_CODE[code]
  return mapped === undefined ? 500 : mapped
}

/* ------------------------------------------------------------------ *
 * Token + 401 plumbing
 * ------------------------------------------------------------------ */
type UnauthorizedHandler = () => void
let onUnauthorized: UnauthorizedHandler | null = null
let onGlobalError: ((err: ApiError) => void) | null = null

export function onUnauthorizedHandler(fn: UnauthorizedHandler): void {
  onUnauthorized = fn
}
export function onGlobalErrorHandler(fn: (err: ApiError) => void): void {
  onGlobalError = fn
}

export function getToken(): string | null {
  try {
    return localStorage.getItem(TOKEN_KEY)
  } catch {
    return null
  }
}

export function setToken(token: string | null): void {
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token)
    else localStorage.removeItem(TOKEN_KEY)
  } catch {
    /* storage unavailable (private mode) — session stays in-memory only */
  }
}

/** Kept for import compatibility — nothing builds URLs any more. */
export function apiUrl(path: string): string {
  return `${API_BASE}/${path.startsWith('/') ? path.slice(1) : path}`
}

function token(): string {
  return getToken() ?? ''
}

/* ------------------------------------------------------------------ *
 * Call plumbing
 * ------------------------------------------------------------------ */
type Pair<T> = [T | null, Bindings.APIError | null]

interface CallOptions {
  /** Suppress the global error toast (the caller handles it). */
  quiet?: boolean
  /** Label used when a method answers `nil, nil` (should not happen). */
  label?: string
}

function toApiError(err: Bindings.APIError): ApiError {
  const code = err.code || 'internal_error'
  return new ApiError(statusForCode(code), code, err.message || 'Request Failed', err.details)
}

function report(err: ApiError, quiet: boolean): ApiError {
  if (err.isUnauthorized) {
    setToken(null)
    onUnauthorized?.()
  } else if (!quiet) {
    onGlobalError?.(err)
  }
  return err
}

/** Unwraps a `[value, error]` service result into a value or a thrown ApiError. */
async function call<T>(invoke: CancellablePromise<Pair<T>>, opts: CallOptions = {}): Promise<T> {
  const { quiet = false, label = 'service' } = opts
  let result: Pair<T>
  try {
    result = await invoke
  } catch (e) {
    // No Wails host, cancelled call, wrong argument count, … — keep the single
    // failure shape the app already handles.
    throw report(new ApiError(0, 'network_error', (e as Error)?.message || 'Request Failed'), quiet)
  }
  const [value, apiError] = result
  if (apiError) throw report(toApiError(apiError), quiet)
  if (value === null || value === undefined) {
    throw report(new ApiError(500, 'internal_error', `${label} 返回空结果`), quiet)
  }
  return value
}

/** Same, for the few service methods that answer with a bare value. */
async function callValue<T>(invoke: CancellablePromise<T | null>, opts: CallOptions = {}): Promise<T> {
  const { quiet = false, label = 'service' } = opts
  let value: T | null
  try {
    value = await invoke
  } catch (e) {
    throw report(new ApiError(0, 'network_error', (e as Error)?.message || 'Request Failed'), quiet)
  }
  if (value === null || value === undefined) {
    throw report(new ApiError(500, 'internal_error', `${label} 返回空结果`), quiet)
  }
  return value
}

/* ------------------------------------------------------------------ *
 * Model adapters — Go structs → types.ts envelopes
 * ------------------------------------------------------------------ */
function compact<T>(list: readonly (T | null)[] | null | undefined): T[] {
  return (list ?? []).filter((item): item is T => item !== null && item !== undefined)
}

/** Go sends `""` / an omitted field where the API contract declares `null`. */
function nullable(value: string | null | undefined): string | null {
  return value ? value : null
}

function toQuota(q: Store.Quota | null | undefined): Quota {
  if (!q) {
    return {
      plan: 'free',
      is_member: false,
      links_used: 0,
      links_limit: 0,
      links_unlimited: false,
      files_used: 0,
      files_limit: 0,
      files_unlimited: false,
      concurrent_limit: 0,
      concurrent_running: 0,
    }
  }
  return {
    plan: q.plan as Quota['plan'],
    is_member: q.is_member,
    links_used: q.links_used,
    links_limit: q.links_limit,
    links_unlimited: q.links_unlimited,
    files_used: q.files_used,
    files_limit: q.files_limit,
    files_unlimited: q.files_unlimited,
    concurrent_limit: q.concurrent_limit,
    concurrent_running: q.concurrent_running,
  }
}

/** `store.User` has no `is_member` field, so it is derived from the quota. */
function toUser(u: Store.User | null | undefined, quota?: Quota | null): User {
  if (!u) {
    return {
      id: 0,
      username: '',
      email: '',
      role: 'user',
      plan: 'free',
      plan_expires_at: null,
      is_member: false,
      created_at: '',
    }
  }
  return {
    id: u.id,
    username: u.username,
    email: u.email,
    role: u.role as User['role'],
    plan: u.plan as User['plan'],
    plan_expires_at: nullable(u.plan_expires_at),
    is_member: quota ? quota.is_member : u.plan === 'member',
    created_at: u.created_at,
  }
}

function toTaskOptions(o: Store.TaskOptions | null | undefined): TaskOptions {
  return {
    max_retries: o?.max_retries ?? 0,
    connections: o?.connections ?? 0,
    rate_limit_kbps: o?.rate_limit_kbps ?? 0,
    ignore: o?.ignore ?? [],
    include: o?.include ?? [],
    no_album_folder: o?.no_album_folder ?? false,
    clean_name: o?.clean_name ?? false,
    custom_path: nullable(o?.custom_path) ?? undefined,
  }
}

function toTaskOptionsInput(o: TaskOptions): Bindings.TaskOptionsInput {
  return {
    max_retries: o.max_retries,
    connections: o.connections,
    rate_limit_kbps: o.rate_limit_kbps,
    ignore: o.ignore ?? [],
    include: o.include ?? [],
    no_album_folder: o.no_album_folder,
    clean_name: o.clean_name,
    custom_path: o.custom_path ?? '',
  }
}

function toTask(t: Store.Task | null | undefined): Task {
  return {
    id: t?.id ?? 0,
    user_id: t?.user_id ?? 0,
    url: t?.url ?? '',
    kind: t?.kind ?? 'item',
    album_id: nullable(t?.album_id),
    album_name: nullable(t?.album_name),
    status: (t?.status ?? 'pending') as TaskStatus,
    download_path: t?.download_path ?? '',
    options: toTaskOptions(t?.options),
    error_message: nullable(t?.error_message),
    total_files: t?.total_files ?? 0,
    completed_files: t?.completed_files ?? 0,
    failed_files: t?.failed_files ?? 0,
    skipped_files: t?.skipped_files ?? 0,
    pending_files: t?.pending_files ?? 0,
    downloading_files: t?.downloading_files ?? 0,
    total_bytes: t?.total_bytes ?? 0,
    downloaded_bytes: t?.downloaded_bytes ?? 0,
    speed: t?.speed ?? 0,
    progress: t?.progress ?? 0,
    created_at: t?.created_at ?? '',
    started_at: nullable(t?.started_at),
    finished_at: nullable(t?.finished_at),
    updated_at: t?.updated_at ?? '',
  }
}

function toFile(f: Store.File | null | undefined): DownloadFile {
  return {
    id: f?.id ?? 0,
    task_id: f?.task_id ?? 0,
    item_url: f?.item_url ?? '',
    filename: f?.filename ?? '',
    download_link: nullable(f?.download_link),
    gid: nullable(f?.gid),
    file_size: f?.file_size ?? 0,
    downloaded_bytes: f?.downloaded_bytes ?? 0,
    speed: f?.speed ?? 0,
    progress: f?.progress ?? 0,
    status: (f?.status ?? 'pending') as FileStatus,
    retry_count: f?.retry_count ?? 0,
    error_message: nullable(f?.error_message),
    item_date: nullable(f?.item_date),
    created_at: f?.created_at ?? '',
    started_at: nullable(f?.started_at),
    finished_at: nullable(f?.finished_at),
    updated_at: f?.updated_at ?? '',
  }
}

function toEvent(e: Store.Event | null | undefined): TaskEvent {
  return {
    id: e?.id ?? 0,
    // Go models a missing task as `null`; the API contract uses 0 and the store
    // drops those events (they are not tied to the open task).
    task_id: e?.task_id ?? 0,
    file_id: e?.file_id ?? null,
    level: (e?.level || 'info') as EventLevel,
    event: e?.event ?? '',
    details: nullable(e?.details),
    created_at: e?.created_at ?? '',
  }
}

function toOrder(o: Store.Order | null | undefined): Order {
  return {
    id: o?.id ?? 0,
    user_id: o?.user_id ?? 0,
    plan: (o?.plan ?? 'free') as PlanId,
    amount_cents: o?.amount_cents ?? 0,
    currency: o?.currency ?? '',
    status: (o?.status ?? 'pending') as OrderStatus,
    provider: o?.provider ?? '',
    trade_no: o?.trade_no ?? '',
    created_at: o?.created_at ?? '',
    paid_at: nullable(o?.paid_at),
    expires_at: nullable(o?.expires_at),
  }
}

function toPlan(p: Store.Plan | null | undefined): PlanItem {
  return {
    id: (p?.id ?? 'free') as PlanId,
    name: p?.name ?? '',
    price_cents: p?.price_cents ?? 0,
    currency: p?.currency ?? '',
    period_days: p?.period_days ?? 0,
    features: p?.features ?? [],
    limits: {
      links: p?.limits?.links ?? 0,
      files: p?.limits?.files ?? 0,
      concurrent: p?.limits?.concurrent ?? 0,
    },
  }
}

function toAria2Globals(s: Bindings.Stats): Aria2Globals {
  return {
    download_speed: s.aria2?.download_speed ?? 0,
    active: s.aria2?.active ?? 0,
    waiting: s.aria2?.waiting ?? 0,
    stopped: s.aria2?.stopped ?? 0,
    num_of_files: s.aria2?.num_of_files ?? 0,
  }
}

function toStats(s: Bindings.Stats): Stats {
  return {
    total_tasks: s.total_tasks,
    running: s.running,
    pending: s.pending,
    paused: s.paused,
    completed: s.completed,
    failed: s.failed,
    canceled: s.canceled,
    total_files: s.total_files,
    completed_files: s.completed_files,
    downloaded_bytes: s.downloaded_bytes,
    speed: s.speed,
    active_files: s.active_files,
    aria2: toAria2Globals(s),
    quota: toQuota(s.quota),
  }
}

function toHealth(h: Bindings.Health): Health {
  return {
    status: h.status,
    version: h.version,
    uptime_seconds: h.uptime_seconds,
    aria2: { available: h.aria2?.available ?? false, version: h.aria2?.version ?? '' },
  }
}

function toSettings(s: Bindings.Settings): AppSettings {
  const features = s.features ?? {}
  return {
    download_dir: s.download_dir,
    version: s.version,
    features: {
      aria2: Boolean(features.aria2),
      payment: String(features.payment ?? ''),
      desktop: Boolean(features.desktop),
    },
  }
}

function toAuthRes(s: Bindings.Session): AuthRes {
  const quota = toQuota(s.quota)
  return { user: toUser(s.user, quota), token: nullable(s.token) ?? undefined, quota }
}

/* ------------------------------------------------------------------ *
 * §2 Auth
 * ------------------------------------------------------------------ */
export const authApi = {
  register: async (body: RegisterReq): Promise<AuthRes> =>
    toAuthRes(await call(AuthService.Register(body.username, body.email, body.password), { label: 'register' })),
  login: async (body: LoginReq): Promise<AuthRes> =>
    toAuthRes(await call(AuthService.Login(body.account, body.password), { label: 'login' })),
  /** Best-effort: the local session is dropped by the caller either way. */
  logout: async (): Promise<OkRes> => {
    try {
      await AuthService.Logout(token())
    } catch {
      /* no host / service gone — the token is discarded regardless */
    }
    return { ok: true }
  },
  /** Silent: a 401 here is the normal "session expired" path, not a toast. */
  me: async (): Promise<AuthRes> =>
    toAuthRes(await call(AuthService.Me(token()), { quiet: true, label: 'me' })),
  changePassword: async (body: ChangePasswordReq): Promise<OkRes> => {
    await call(
      AuthService.ChangePassword(token(), body.old_password, body.new_password),
      { label: 'changePassword' },
    )
    return { ok: true }
  },
}

/* ------------------------------------------------------------------ *
 * §3 Membership
 * ------------------------------------------------------------------ */
export const membershipApi = {
  plans: async (): Promise<PlansRes> => {
    const res = await callValue(MembershipService.Plans(), { label: 'plans' })
    return { plans: compact(res.plans).map(toPlan) }
  },
  status: async (): Promise<MembershipStatusRes> => {
    const s = await call(MembershipService.Status(token()), { label: 'membershipStatus' })
    return {
      plan: (s.plan || 'free') as PlanId,
      is_member: s.is_member,
      expires_at: nullable(s.expires_at),
      quota: toQuota(s.quota),
    }
  },
  createOrder: async (body: CreateOrderReq): Promise<CreateOrderRes> => ({
    order: toOrder(await call(MembershipService.CreateOrder(token(), body.plan), { label: 'createOrder' })),
  }),
  orders: async (): Promise<ListOrdersRes> => {
    const res = await call(MembershipService.ListOrders(token()), { label: 'orders' })
    return { orders: compact(res.orders).map(toOrder) }
  },
  pay: async (id: number, body: PayOrderReq): Promise<PayOrderRes> => {
    const res = await call(
      MembershipService.PayOrder(token(), id, body?.pay_method ?? 'alipay'),
      { label: 'payOrder' },
    )
    const quota = toQuota(res.quota)
    return { order: toOrder(res.order), user: toUser(res.user, quota), quota }
  },
  cancelOrder: async (body: CancelOrderReq): Promise<CancelOrderRes> => ({
    order: toOrder(await call(MembershipService.CancelOrder(token(), body.order_id), { label: 'cancelOrder' })),
  }),
  redeem: async (body: RedeemReq): Promise<RedeemRes> => {
    const session = await call(MembershipService.Redeem(token(), body.code), { label: 'redeem' })
    const quota = toQuota(session.quota)
    return { user: toUser(session.user, quota), quota }
  },
}

/* ------------------------------------------------------------------ *
 * §4 Tasks
 * ------------------------------------------------------------------ */
export type TaskActionResponse = TaskActionRes & { retried?: number }

export const tasksApi = {
  list: async (q?: ListTasksQuery): Promise<ListTasksRes> => {
    const res = await call(
      TaskService.ListTasks(
        token(),
        q?.status ?? '',
        q?.q ?? '',
        q?.sort ?? '',
        q?.order ?? '',
        q?.limit ?? 50,
        q?.offset ?? 0,
      ),
      { label: 'listTasks' },
    )
    return { tasks: compact(res.tasks).map(toTask), total: res.total }
  },
  create: async (body: CreateTaskReq): Promise<CreateTaskRes> => {
    const res = await call(
      TaskService.CreateTask(token(), {
        url: body.url,
        urls: [],
        options: toTaskOptionsInput(body.options),
        auto_start: body.auto_start,
      }),
      { label: 'createTask' },
    )
    return { task_ids: res.task_ids ?? [], count: res.count, quota: toQuota(res.quota) }
  },
  detail: async (id: number): Promise<TaskDetailRes> => {
    const res = await call(TaskService.GetTask(token(), id), { label: 'taskDetail' })
    const task = toTask(res.task)
    // The web endpoint mirrored the task as `stats`; the binding returns the
    // per-status file summary instead.
    return { task, stats: task, files_summary: res.files_summary ?? {} }
  },
  remove: async (id: number): Promise<DeleteTaskRes> => {
    await call(TaskService.DeleteTask(token(), id), { label: 'deleteTask' })
    return { ok: true, deleted: id }
  },
  action: async (
    id: number,
    act: 'start' | 'pause' | 'resume' | 'cancel' | 'retry',
    body?: TaskActionReq,
  ): Promise<TaskActionResponse> => {
    if (act === 'retry') {
      const retried = await call(TaskService.Retry(token(), id, body?.files ?? []), { label: 'retryTask' })
      // Retry answers with the number of re-queued files, so the refreshed task
      // is read back for the store to replace.
      const detail = await call(TaskService.GetTask(token(), id), { label: 'taskDetail' })
      return { ok: true, retried, task: toTask(detail.task) }
    }
    const invoke =
      act === 'start'
        ? TaskService.Start(token(), id)
        : act === 'pause'
          ? TaskService.Pause(token(), id)
          : act === 'resume'
            ? TaskService.Resume(token(), id)
            : TaskService.Cancel(token(), id)
    return { ok: true, task: toTask(await call(invoke, { label: `task:${act}` })) }
  },
  files: async (id: number, q?: ListFilesQuery): Promise<ListFilesRes> => {
    const res = await call(
      TaskService.ListFiles(
        token(),
        id,
        q?.status ?? '',
        q?.q ?? '',
        q?.sort ?? '',
        q?.order ?? '',
        q?.limit ?? 50,
        q?.offset ?? 0,
      ),
      { label: 'listFiles' },
    )
    return {
      files: compact(res.files).map(toFile),
      total: res.total,
      limit: res.limit,
      offset: res.offset,
    }
  },
  retryFile: async (id: number, fileId: number): Promise<FileActionRes> => ({
    ok: true,
    file: toFile(await call(TaskService.RetryFile(token(), id, fileId), { label: 'retryFile' })),
  }),
  events: async (id: number, q?: ListEventsQuery): Promise<ListEventsRes> => {
    const res = await call(
      TaskService.ListEvents(token(), id, q?.before_id ?? 0, q?.limit ?? 200),
      { label: 'listEvents' },
    )
    return { events: compact(res.events).map(toEvent) }
  },
  recentEvents: async (limit = 50): Promise<ListEventsRes> => {
    const res = await call(TaskService.ListEvents(token(), 0, 0, limit), { label: 'recentEvents' })
    return { events: compact(res.events).map(toEvent) }
  },
}

/* ------------------------------------------------------------------ *
 * §5 System
 * ------------------------------------------------------------------ */
export const systemApi = {
  health: async (): Promise<Health> =>
    toHealth(await callValue(SystemService.Health(), { label: 'health' })),
  stats: async (): Promise<Stats> => toStats(await call(SystemService.Stats(token()), { label: 'stats' })),
  settings: async (): Promise<AppSettings> =>
    toSettings(await callValue(SystemService.Settings(), { label: 'settings' })),
  /** Desktop-only: changes and persists where new downloads are stored. */
  setDownloadDir: async (path: string): Promise<AppSettings> =>
    toSettings(await call(SystemService.SetDownloadDir(token(), path), { label: 'settings' })),
  /** Desktop-only: reveals the download folder in the OS file manager. */
  openDownloadDir: async (): Promise<string> => {
    const [ok, message] = await SystemService.OpenDownloadDir()
    if (!ok) throw new ApiError(0, 'internal_error', message || '无法打开下载目录')
    return message
  },
  /** Desktop-only: restarts the aria2c process. */
  aria2Restart: async (): Promise<string> => {
    const [ok, message] = await SystemService.Aria2Restart()
    if (!ok) throw new ApiError(0, 'internal_error', message || 'aria2 重启失败')
    return message
  },
  aria2BinaryPath: async (): Promise<string> => SystemService.Aria2BinaryPath(),
  dataDir: async (): Promise<string> => SystemService.DataDir(),
  revealPath: async (path: string): Promise<string> => {
    const [ok, message] = await SystemService.RevealPath(path)
    if (!ok) throw new ApiError(0, 'internal_error', message || '无法定位文件')
    return message
  },
}
