// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService covers registration, login and the session endpoints.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePassword rotates the account password.
 * @param {string} token
 * @param {string} oldPassword
 * @param {string} newPassword
 * @returns {$CancellablePromise<[boolean, $models.APIError | null]>}
 */
export function ChangePassword(token, oldPassword, newPassword) {
    return $Call.ByID(3816575872, token, oldPassword, newPassword).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType1($result[1]);
        return $result;
    }));
}

/**
 * Login authenticates by username or email.
 * @param {string} account
 * @param {string} password
 * @returns {$CancellablePromise<[$models.Session | null, $models.APIError | null]>}
 */
export function Login(account, password) {
    return $Call.ByID(3371616786, account, password).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    }));
}

/**
 * Logout drops the local session. Tokens stay stateless, so this is a no-op
 * on the server; the frontend discards the token.
 * @param {string} token
 * @returns {$CancellablePromise<boolean>}
 */
export function Logout(token) {
    return $Call.ByID(1542891851, token);
}

/**
 * Me returns the current session and quota.
 * @param {string} token
 * @returns {$CancellablePromise<[$models.Session | null, $models.APIError | null]>}
 */
export function Me(token) {
    return $Call.ByID(1292125447, token).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    }));
}

/**
 * Register creates an account and signs the user in.
 * @param {string} username
 * @param {string} email
 * @param {string} password
 * @returns {$CancellablePromise<[$models.Session | null, $models.APIError | null]>}
 */
export function Register(username, email, password) {
    return $Call.ByID(3741417504, username, email, password).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = $models.APIError.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Session.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
