// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MembershipService covers plans, orders, payment and redemption codes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelOrder cancels a pending order.
 * @param {string} token
 * @param {number} orderID
 * @returns {$CancellablePromise<[store$0.Order | null, $models.APIError | null]>}
 */
export function CancelOrder(token, orderID) {
    return $Call.ByID(1457536759, token, orderID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * CreateOrder opens a pending membership order.
 * @param {string} token
 * @param {string} plan
 * @returns {$CancellablePromise<[store$0.Order | null, $models.APIError | null]>}
 */
export function CreateOrder(token, plan) {
    return $Call.ByID(1400693493, token, plan).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * ListOrders returns the caller's orders, newest first.
 * @param {string} token
 * @returns {$CancellablePromise<[$models.Orders | null, $models.APIError | null]>}
 */
export function ListOrders(token) {
    return $Call.ByID(1697670362, token).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType5($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * PayOrder settles an order through the mock gateway and upgrades the plan.
 * @param {string} token
 * @param {number} orderID
 * @param {string} payMethod
 * @returns {$CancellablePromise<[$models.PayResult | null, $models.APIError | null]>}
 */
export function PayOrder(token, orderID, payMethod) {
    return $Call.ByID(21676149, token, orderID, payMethod).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType7($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Plans returns the plan catalogue.
 * @returns {$CancellablePromise<$models.Plans | null>}
 */
export function Plans() {
    return $Call.ByID(2860510621).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Redeem activates a membership from a code.
 * @param {string} token
 * @param {string} code
 * @returns {$CancellablePromise<[$models.Session | null, $models.APIError | null]>}
 */
export function Redeem(token, code) {
    return $Call.ByID(3352485303, token, code).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType11($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Status reports the caller's plan and allowance.
 * @param {string} token
 * @returns {$CancellablePromise<[$models.Status | null, $models.APIError | null]>}
 */
export function Status(token) {
    return $Call.ByID(2074310133, token).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType13($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = store$0.Order.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.APIError.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Orders.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.PayResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.Plans.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.Session.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.Status.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
