// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * APIError is the error payload every service returns instead of a Go error.
 * The frontend renders Message directly, so it is always user-facing Chinese.
 */
export class APIError {
    /**
     * Creates a new APIError instance.
     * @param {Partial<APIError>} [$$source = {}] - The source object to create the APIError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIError}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new APIError(/** @type {Partial<APIError>} */($$parsedSource));
    }
}

/**
 * Aria2Info is the download engine status block.
 */
export class Aria2Info {
    /**
     * Creates a new Aria2Info instance.
     * @param {Partial<Aria2Info>} [$$source = {}] - The source object to create the Aria2Info.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["binary"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Aria2Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Aria2Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Aria2Info(/** @type {Partial<Aria2Info>} */($$parsedSource));
    }
}

/**
 * CreateResult reports the created task ids and the refreshed quota.
 */
export class CreateResult {
    /**
     * Creates a new CreateResult instance.
     * @param {Partial<CreateResult>} [$$source = {}] - The source object to create the CreateResult.
     */
    constructor($$source = {}) {
        if (!("task_ids" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["task_ids"] = [];
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {store$0.Quota | null}
             */
            this["quota"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task_ids" in $$parsedSource) {
            $$parsedSource["task_ids"] = $$createField0_0($$parsedSource["task_ids"]);
        }
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField2_0($$parsedSource["quota"]);
        }
        return new CreateResult(/** @type {Partial<CreateResult>} */($$parsedSource));
    }
}

/**
 * CreateTaskRequest is the payload for CreateTask.
 */
export class CreateTaskRequest {
    /**
     * Creates a new CreateTaskRequest instance.
     * @param {Partial<CreateTaskRequest>} [$$source = {}] - The source object to create the CreateTaskRequest.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * URL accepts a newline-separated list, mirroring the web UI.
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("urls" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["urls"] = [];
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {TaskOptionsInput | null}
             */
            this["options"] = null;
        }
        if (!("auto_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTaskRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField1_0($$parsedSource["urls"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new CreateTaskRequest(/** @type {Partial<CreateTaskRequest>} */($$parsedSource));
    }
}

/**
 * EventList wraps task events.
 */
export class EventList {
    /**
     * Creates a new EventList instance.
     * @param {Partial<EventList>} [$$source = {}] - The source object to create the EventList.
     */
    constructor($$source = {}) {
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {(store$0.Event | null)[]}
             */
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventList}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField0_0($$parsedSource["events"]);
        }
        return new EventList(/** @type {Partial<EventList>} */($$parsedSource));
    }
}

/**
 * FileList is the paged result of ListFiles.
 */
export class FileList {
    /**
     * Creates a new FileList instance.
     * @param {Partial<FileList>} [$$source = {}] - The source object to create the FileList.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {(store$0.File | null)[]}
             */
            this["files"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileList}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new FileList(/** @type {Partial<FileList>} */($$parsedSource));
    }
}

/**
 * Health mirrors GET /api/health.
 */
export class Health {
    /**
     * Creates a new Health instance.
     * @param {Partial<Health>} [$$source = {}] - The source object to create the Health.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("uptime_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptime_seconds"] = 0;
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("aria2" in $$source)) {
            /**
             * @member
             * @type {Aria2Info}
             */
            this["aria2"] = (new Aria2Info());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Health}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aria2" in $$parsedSource) {
            $$parsedSource["aria2"] = $$createField4_0($$parsedSource["aria2"]);
        }
        return new Health(/** @type {Partial<Health>} */($$parsedSource));
    }
}

/**
 * Orders lists the caller's purchase history.
 */
export class Orders {
    /**
     * Creates a new Orders instance.
     * @param {Partial<Orders>} [$$source = {}] - The source object to create the Orders.
     */
    constructor($$source = {}) {
        if (!("orders" in $$source)) {
            /**
             * @member
             * @type {(store$0.Order | null)[]}
             */
            this["orders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Orders instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Orders}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orders" in $$parsedSource) {
            $$parsedSource["orders"] = $$createField0_0($$parsedSource["orders"]);
        }
        return new Orders(/** @type {Partial<Orders>} */($$parsedSource));
    }
}

/**
 * PayResult reports the settled order plus the upgraded session.
 */
export class PayResult {
    /**
     * Creates a new PayResult instance.
     * @param {Partial<PayResult>} [$$source = {}] - The source object to create the PayResult.
     */
    constructor($$source = {}) {
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {store$0.Order | null}
             */
            this["order"] = null;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {store$0.User | null}
             */
            this["user"] = null;
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {store$0.Quota | null}
             */
            this["quota"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PayResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PayResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField0_0($$parsedSource["order"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField2_0($$parsedSource["quota"]);
        }
        return new PayResult(/** @type {Partial<PayResult>} */($$parsedSource));
    }
}

/**
 * Plans is the public price list.
 */
export class Plans {
    /**
     * Creates a new Plans instance.
     * @param {Partial<Plans>} [$$source = {}] - The source object to create the Plans.
     */
    constructor($$source = {}) {
        if (!("plans" in $$source)) {
            /**
             * @member
             * @type {store$0.Plan[]}
             */
            this["plans"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plans instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plans}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plans" in $$parsedSource) {
            $$parsedSource["plans"] = $$createField0_0($$parsedSource["plans"]);
        }
        return new Plans(/** @type {Partial<Plans>} */($$parsedSource));
    }
}

/**
 * Session is what Register/Login return.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {store$0.User | null}
             */
            this["user"] = null;
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {store$0.Quota | null}
             */
            this["quota"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType18;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField0_0($$parsedSource["user"]);
        }
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField2_0($$parsedSource["quota"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

/**
 * Settings describes the desktop app's configuration to the UI.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("download_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_dir"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("features" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["features"] = {};
        }
        if (!("defaults" in $$source)) {
            /**
             * @member
             * @type {store$0.TaskOptions}
             */
            this["defaults"] = (new store$0.TaskOptions());
        }
        if (!("quota_limits" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["quota_limits"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField3_0($$parsedSource["features"]);
        }
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField4_0($$parsedSource["defaults"]);
        }
        if ("quota_limits" in $$parsedSource) {
            $$parsedSource["quota_limits"] = $$createField5_0($$parsedSource["quota_limits"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Stats mirrors GET /api/stats.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("total_tasks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tasks"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["paused"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("canceled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["canceled"] = 0;
        }
        if (!("total_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_files"] = 0;
        }
        if (!("completed_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed_files"] = 0;
        }
        if (!("downloaded_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded_bytes"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("active_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active_files"] = 0;
        }
        if (!("aria2" in $$source)) {
            /**
             * @member
             * @type {downloadsAria2Stat}
             */
            this["aria2"] = (new downloadsAria2Stat());
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {store$0.Quota | null}
             */
            this["quota"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType22;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aria2" in $$parsedSource) {
            $$parsedSource["aria2"] = $$createField12_0($$parsedSource["aria2"]);
        }
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField13_0($$parsedSource["quota"]);
        }
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * Status is the membership summary shown in the header.
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plan"] = "";
        }
        if (!("is_member" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_member"] = false;
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["expires_at"] = null;
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {store$0.Quota | null}
             */
            this["quota"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField3_0($$parsedSource["quota"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * TaskDetail is a task plus its per-status file summary.
 */
export class TaskDetail {
    /**
     * Creates a new TaskDetail instance.
     * @param {Partial<TaskDetail>} [$$source = {}] - The source object to create the TaskDetail.
     */
    constructor($$source = {}) {
        if (!("task" in $$source)) {
            /**
             * @member
             * @type {store$0.Task | null}
             */
            this["task"] = null;
        }
        if (!("files_summary" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["files_summary"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField0_0($$parsedSource["task"]);
        }
        if ("files_summary" in $$parsedSource) {
            $$parsedSource["files_summary"] = $$createField1_0($$parsedSource["files_summary"]);
        }
        return new TaskDetail(/** @type {Partial<TaskDetail>} */($$parsedSource));
    }
}

/**
 * TaskList is the paged result of ListTasks.
 */
export class TaskList {
    /**
     * Creates a new TaskList instance.
     * @param {Partial<TaskList>} [$$source = {}] - The source object to create the TaskList.
     */
    constructor($$source = {}) {
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {(store$0.Task | null)[]}
             */
            this["tasks"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskList}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        return new TaskList(/** @type {Partial<TaskList>} */($$parsedSource));
    }
}

/**
 * TaskOptionsInput mirrors the web API's per-task options.
 */
export class TaskOptionsInput {
    /**
     * Creates a new TaskOptionsInput instance.
     * @param {Partial<TaskOptionsInput>} [$$source = {}] - The source object to create the TaskOptionsInput.
     */
    constructor($$source = {}) {
        if (!("max_retries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_retries"] = 0;
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections"] = 0;
        }
        if (!("rate_limit_kbps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rate_limit_kbps"] = 0;
        }
        if (!("ignore" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ignore"] = [];
        }
        if (!("include" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include"] = [];
        }
        if (!("no_album_folder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["no_album_folder"] = false;
        }
        if (!("clean_name" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clean_name"] = false;
        }
        if (!("custom_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["custom_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskOptionsInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskOptionsInput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignore" in $$parsedSource) {
            $$parsedSource["ignore"] = $$createField3_0($$parsedSource["ignore"]);
        }
        if ("include" in $$parsedSource) {
            $$parsedSource["include"] = $$createField4_0($$parsedSource["include"]);
        }
        return new TaskOptionsInput(/** @type {Partial<TaskOptionsInput>} */($$parsedSource));
    }
}

export class downloadsAria2Stat {
    /**
     * Creates a new downloadsAria2Stat instance.
     * @param {Partial<downloadsAria2Stat>} [$$source = {}] - The source object to create the downloadsAria2Stat.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("download_speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["download_speed"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active"] = 0;
        }
        if (!("waiting" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["waiting"] = 0;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stopped"] = 0;
        }
        if (!("num_of_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["num_of_files"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new downloadsAria2Stat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {downloadsAria2Stat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new downloadsAria2Stat(/** @type {Partial<downloadsAria2Stat>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = store$0.Quota.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = TaskOptionsInput.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = store$0.Event.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = store$0.File.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Aria2Info.createFrom;
const $$createType14 = store$0.Order.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = store$0.User.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = store$0.Plan.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = store$0.TaskOptions.createFrom;
const $$createType22 = downloadsAria2Stat.createFrom;
const $$createType23 = store$0.Task.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Map($Create.Any, $Create.Any);
const $$createType26 = $Create.Array($$createType24);
