// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes runtime information and desktop conveniences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Aria2BinaryPath reports the resolved aria2c executable, which is the value
 * the settings screen should show.
 * @returns {$CancellablePromise<string>}
 */
export function Aria2BinaryPath() {
    return $Call.ByID(2532092009);
}

/**
 * Aria2Restart forces a fresh aria2c process. Useful after a manual binary
 * upgrade or when the engine reports itself unhealthy.
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function Aria2Restart() {
    return $Call.ByID(154447934);
}

/**
 * DataDir reports where the database and the aria2 session live.
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByID(2912237037);
}

/**
 * Health reports liveness plus the aria2 engine state.
 * @returns {$CancellablePromise<$models.Health | null>}
 */
export function Health() {
    return $Call.ByID(315232644).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenDownloadDir reveals the download folder in the OS file manager.
 * This is a desktop-only affordance the web build cannot offer.
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenDownloadDir() {
    return $Call.ByID(1779708501);
}

/**
 * RevealPath shows a specific file or folder, falling back to the parent dir.
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function RevealPath(path) {
    return $Call.ByID(3106637372, path);
}

/**
 * SetDownloadDir changes where new downloads are stored and persists the
 * choice so it survives a restart. Tasks that already resolved to a custom
 * path keep it; existing default-path tasks keep the folder they were created
 * with. Returns the refreshed settings so the UI can re-sync immediately.
 * @param {string} token
 * @param {string} path
 * @returns {$CancellablePromise<[$models.Settings | null, $models.APIError | null]>}
 */
export function SetDownloadDir(token, path) {
    return $Call.ByID(596926573, token, path).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        $result[1] = $$createType5($result[1]);
        return $result;
    }));
}

/**
 * Settings returns the non-secret runtime configuration.
 * @returns {$CancellablePromise<$models.Settings | null>}
 */
export function Settings() {
    return $Call.ByID(3276553411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Stats returns the dashboard counters.
 * @param {string} token
 * @returns {$CancellablePromise<[$models.Stats | null, $models.APIError | null]>}
 */
export function Stats(token) {
    return $Call.ByID(1949627277, token).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType7($result[0]);
        $result[1] = $$createType5($result[1]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = $models.Health.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.APIError.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.Stats.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
