// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService exposes the download manager to the desktop UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel aborts a task and skips the remaining files.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[store$0.Task | null, $models.APIError | null]>}
 */
export function Cancel(token, taskID) {
    return $Call.ByID(4146143176, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * CreateTask validates, quota-checks and creates one or more tasks.
 * @param {string} token
 * @param {$models.CreateTaskRequest} req
 * @returns {$CancellablePromise<[$models.CreateResult | null, $models.APIError | null]>}
 */
export function CreateTask(token, req) {
    return $Call.ByID(4107380883, token, req).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType5($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * DeleteTask cancels and removes a task.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[boolean, $models.APIError | null]>}
 */
export function DeleteTask(token, taskID) {
    return $Call.ByID(470417004, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * GetTask returns one task owned by the caller.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[$models.TaskDetail | null, $models.APIError | null]>}
 */
export function GetTask(token, taskID) {
    return $Call.ByID(760987563, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType7($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * ListEvents returns a task's log, newest first.
 * @param {string} token
 * @param {number} taskID
 * @param {number} beforeID
 * @param {number} limit
 * @returns {$CancellablePromise<[$models.EventList | null, $models.APIError | null]>}
 */
export function ListEvents(token, taskID, beforeID, limit) {
    return $Call.ByID(1172927299, token, taskID, beforeID, limit).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType9($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * ListFiles returns a page of a task's files.
 * @param {string} token
 * @param {number} taskID
 * @param {string} status
 * @param {string} query
 * @param {string} sort
 * @param {string} dir
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<[$models.FileList | null, $models.APIError | null]>}
 */
export function ListFiles(token, taskID, status, query, sort, dir, limit, offset) {
    return $Call.ByID(2190264281, token, taskID, status, query, sort, dir, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType11($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * ListTasks returns a filtered page of the caller's tasks.
 * @param {string} token
 * @param {string} status
 * @param {string} query
 * @param {string} sort
 * @param {string} dir
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<[$models.TaskList | null, $models.APIError | null]>}
 */
export function ListTasks(token, status, query, sort, dir, limit, offset) {
    return $Call.ByID(1022509864, token, status, query, sort, dir, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType13($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Pause suspends a task's transfers.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[store$0.Task | null, $models.APIError | null]>}
 */
export function Pause(token, taskID) {
    return $Call.ByID(4077100940, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Resume continues a paused task from its saved position.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[store$0.Task | null, $models.APIError | null]>}
 */
export function Resume(token, taskID) {
    return $Call.ByID(3797389429, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Retry re-queues a task's failed files (or a specific subset).
 * @param {string} token
 * @param {number} taskID
 * @param {number[]} fileIDs
 * @returns {$CancellablePromise<[number, $models.APIError | null]>}
 */
export function Retry(token, taskID, fileIDs) {
    return $Call.ByID(690297192, token, taskID, fileIDs).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * RetryFile re-queues a single file.
 * @param {string} token
 * @param {number} taskID
 * @param {number} fileID
 * @returns {$CancellablePromise<[store$0.File | null, $models.APIError | null]>}
 */
export function RetryFile(token, taskID, fileID) {
    return $Call.ByID(1157891102, token, taskID, fileID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType15($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * Start begins (or queues) a task.
 * @param {string} token
 * @param {number} taskID
 * @returns {$CancellablePromise<[store$0.Task | null, $models.APIError | null]>}
 */
export function Start(token, taskID) {
    return $Call.ByID(2536692514, token, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

// Private type creation functions
const $$createType0 = store$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.APIError.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.CreateResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TaskDetail.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.EventList.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.FileList.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.TaskList.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = store$0.File.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
