// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Event is a timestamped log line attached to a task and/or file.
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("task_id" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["task_id"] = null;
        }
        if (!("file_id" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["file_id"] = null;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("event" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event"] = "";
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["details"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * File is a single downloadable item inside a task.
 */
export class File {
    /**
     * Creates a new File instance.
     * @param {Partial<File>} [$$source = {}] - The source object to create the File.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("task_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["task_id"] = 0;
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user_id"] = 0;
        }
        if (!("item_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["item_url"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("download_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_link"] = "";
        }
        if (!("gid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gid"] = "";
        }
        if (!("file_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["file_size"] = 0;
        }
        if (!("downloaded_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded_bytes"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("retry_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retry_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_message"] = undefined;
        }
        if (!("item_date" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["item_date"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["started_at"] = null;
        }
        if (!("finished_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["finished_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {File}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File(/** @type {Partial<File>} */($$parsedSource));
    }
}

/**
 * Order records a membership purchase.
 */
export class Order {
    /**
     * Creates a new Order instance.
     * @param {Partial<Order>} [$$source = {}] - The source object to create the Order.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user_id"] = 0;
        }
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plan"] = "";
        }
        if (!("amount_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount_cents"] = 0;
        }
        if (!("currency" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("trade_no" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trade_no"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("paid_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["paid_at"] = null;
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["expires_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Order instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Order}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Order(/** @type {Partial<Order>} */($$parsedSource));
    }
}

/**
 * Plan describes a purchasable membership tier.
 */
export class Plan {
    /**
     * Creates a new Plan instance.
     * @param {Partial<Plan>} [$$source = {}] - The source object to create the Plan.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("price_cents" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["price_cents"] = 0;
        }
        if (!("currency" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currency"] = "";
        }
        if (!("period_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["period_days"] = 0;
        }
        if (!("features" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["features"] = [];
        }
        if (!("limits" in $$source)) {
            /**
             * @member
             * @type {PlanLimits}
             */
            this["limits"] = (new PlanLimits());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plan}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField5_0($$parsedSource["features"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField6_0($$parsedSource["limits"]);
        }
        return new Plan(/** @type {Partial<Plan>} */($$parsedSource));
    }
}

/**
 * PlanLimits is the JSON shape returned to clients for a plan.
 */
export class PlanLimits {
    /**
     * Creates a new PlanLimits instance.
     * @param {Partial<PlanLimits>} [$$source = {}] - The source object to create the PlanLimits.
     */
    constructor($$source = {}) {
        if (!("links" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["links"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("concurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["concurrent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanLimits instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlanLimits}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanLimits(/** @type {Partial<PlanLimits>} */($$parsedSource));
    }
}

/**
 * Quota is the per-user download allowance, serialised in every user payload.
 */
export class Quota {
    /**
     * Creates a new Quota instance.
     * @param {Partial<Quota>} [$$source = {}] - The source object to create the Quota.
     */
    constructor($$source = {}) {
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plan"] = "";
        }
        if (!("is_member" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_member"] = false;
        }
        if (!("links_used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["links_used"] = 0;
        }
        if (!("links_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["links_limit"] = 0;
        }
        if (!("links_unlimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["links_unlimited"] = false;
        }
        if (!("files_used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files_used"] = 0;
        }
        if (!("files_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files_limit"] = 0;
        }
        if (!("files_unlimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["files_unlimited"] = false;
        }
        if (!("concurrent_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["concurrent_limit"] = 0;
        }
        if (!("concurrent_running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["concurrent_running"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Quota instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Quota}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Quota(/** @type {Partial<Quota>} */($$parsedSource));
    }
}

/**
 * Task aggregates the download of one Bunkr URL.
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user_id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("album_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album_id"] = "";
        }
        if (!("album_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album_name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("download_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_path"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {TaskOptions}
             */
            this["options"] = (new TaskOptions());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_message"] = undefined;
        }
        if (!("total_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_files"] = 0;
        }
        if (!("completed_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed_files"] = 0;
        }
        if (!("failed_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed_files"] = 0;
        }
        if (!("skipped_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped_files"] = 0;
        }
        if (!("pending_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_files"] = 0;
        }
        if (!("downloading_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloading_files"] = 0;
        }
        if (!("total_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_bytes"] = 0;
        }
        if (!("downloaded_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded_bytes"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["started_at"] = null;
        }
        if (!("finished_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["finished_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * TaskOptions are the per-task download settings persisted as JSON.
 */
export class TaskOptions {
    /**
     * Creates a new TaskOptions instance.
     * @param {Partial<TaskOptions>} [$$source = {}] - The source object to create the TaskOptions.
     */
    constructor($$source = {}) {
        if (!("max_retries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_retries"] = 0;
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections"] = 0;
        }
        if (!("rate_limit_kbps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rate_limit_kbps"] = 0;
        }
        if (!("ignore" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ignore"] = [];
        }
        if (!("include" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include"] = [];
        }
        if (!("no_album_folder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["no_album_folder"] = false;
        }
        if (!("clean_name" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clean_name"] = false;
        }
        if (!("custom_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["custom_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskOptions}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignore" in $$parsedSource) {
            $$parsedSource["ignore"] = $$createField3_0($$parsedSource["ignore"]);
        }
        if ("include" in $$parsedSource) {
            $$parsedSource["include"] = $$createField4_0($$parsedSource["include"]);
        }
        return new TaskOptions(/** @type {Partial<TaskOptions>} */($$parsedSource));
    }
}

/**
 * User is an account row.
 */
export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plan"] = "";
        }
        if (!("plan_expires_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["plan_expires_at"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PlanLimits.createFrom;
const $$createType2 = TaskOptions.createFrom;
